### PR TITLE
Don't use developer's .miq_performance

### LINKED ISSUE #8: Don't evaluate the homedir configs during tests
If a developer is running the tests and happens to have a `~/.miq_performance` config file in their home directory, it can cause the tests to fail.  This shouldn't happen and we should prevent this from happening.

### PR DESCRIPTION
**Pull request by kbrock**
If a developer has an `.miq_performance` rc configuration file, it will read that file and tests run wonky.

This PR disables the auto detection and auto load for the rc file.

fixes #8

### CODE REVIEW

File: spec/spec_helper.rb [hunk 1]
```diff
@@ -37,7 +37,7 @@
     ManageIQPerformance.instance_variable_set :@config, nil
 
     if defined? ManageIQPerformance::Configuration
-      ManageIQPerformance::Configuration.instance_variable_set :@config_file_location, nil
+      ManageIQPerformance::Configuration.instance_variable_set :@config_file_location, 'disabled'
```
Comment (NickLaMuro) [inline spec/spec_helper.rb]: Maybe use [Tempfile](http://ruby-doc.org/stdlib-2.3.1/libdoc/tempfile/rdoc/Tempfile.html) here instead just incase this is somehow a legit file (#pedantic).

**Comment by kbrock** [comment]
I just used a single Tempfile filename for all tests rather than a different filename for each run.

Think the file is created so it is read for each of them, but since it is an empty file, the defaults will be used

**Comment by NickLaMuro** [comment]
> I just used a single Tempfile.path for all tests rather than a different filename for each run.

Yeah, I think this is fine.  Would have been nice if we could have used `Tempfile` to just give us a path, but no file, but I think this is fine.  Let's ship since this was already great in the first iteration and we can refactor later if we feel it is necessary.

Thanks!
